/**
 * Stable, client-facing error codes. The API always responds with
 * `{ error: { code, message, details? } }` using one of these codes.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  AGE_CONFIRMATION_REQUIRED: 'AGE_CONFIRMATION_REQUIRED',
  UNDER_AGE: 'UNDER_AGE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
  PERSONA_LIMIT_REACHED: 'PERSONA_LIMIT_REACHED',
  PERSONA_CHURN_LIMIT: 'PERSONA_CHURN_LIMIT',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PERSONA_LOCKED: 'PERSONA_LOCKED',
  PIN_INVALID: 'PIN_INVALID',
  PIN_LOCKED_OUT: 'PIN_LOCKED_OUT',
  NUMBER_UNAVAILABLE: 'NUMBER_UNAVAILABLE',
  NUMBER_PAUSED: 'NUMBER_PAUSED',
  OWN_NUMBER: 'OWN_NUMBER',
  NOT_ACCEPTING_REQUESTS: 'NOT_ACCEPTING_REQUESTS',
  REQUEST_COOLDOWN: 'REQUEST_COOLDOWN',
  REQUEST_DAILY_CAP: 'REQUEST_DAILY_CAP',
  REQUEST_ALREADY_PENDING: 'REQUEST_ALREADY_PENDING',
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  CALL_NOT_ALLOWED: 'CALL_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  MEDIA_NOT_ALLOWED: 'MEDIA_NOT_ALLOWED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
  };
}
